KnowledgeHubPortal.WebUI/Controllers/ArticlesController.cs
using Humanizer;
using KnowledgeHubPortal.Domain;
using KnowledgeHubPortal.Domain.Entities;
using KnowledgeHubPortal.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace KnowledgeHubPortal.WebUI.Controllers
{

    public class ArticlesController : Controller
    {

        private IArticlesManager aMgr = null;
        //private IArticlesRepository aRepo = null;
        //private ICatagoryRepository cRepo = null;
        private ICatagoriesManager cMgr = null;

        //public ArticlesController()
        //{
        //    aRepo = new ArticlesRepository();
        //    cRepo = new CatagoryRepository();
        //    aMgr = new ArticlesManager(aRepo);
        //    cMgr = new CatagoryManager(cRepo);
        //}

        public ArticlesController(IArticlesManager aMgr, ICatagoriesManager cMgr)
        {
            this.aMgr = aMgr;
            this.cMgr = cMgr;
        }

        // GET: Articles



        public ActionResult Index(string searchTerm = null)
        {
            var articlesForBrowse = from a in aMgr.GetArticlesForBrowse()
                                    select new ArticlesForBrowseViewModel
                                    {
                                        Title = a.Title,
                                        CatagoryName = a.Catagory.Name,
                                        Description = a.Description,
                                        Submiter = a.Submiter,
                                        Url = a.Url,
                                        WhenSubmited = a.DateSubmited.Humanize(false)
                                    };
            if (searchTerm != null)
            {
                var filtredArticlesForBrowse = from a in articlesForBrowse
                                               where a.Title.ToLower().Contains(searchTerm.ToLower()) ||
                                               a.Description.ToLower().Contains(searchTerm.ToLower()) ||
                                               a.Url.ToLower().Contains(searchTerm.ToLower()) ||
                                               a.CatagoryName.ToLower().Contains(searchTerm.ToLower()) ||
                                               a.Submiter.ToLower().Contains(searchTerm.ToLower())
                                               select a;
                return View(filtredArticlesForBrowse);
            }

            return View(articlesForBrowse);
        }


        [Authorize]
        [HttpGet]
        public ActionResult Submit()
        {
            //var catagories = cMgr.ListCatagories();

            var catagories = from c in cMgr.ListCatagories()
                             select new SelectListItem { Text = c.Name, Value = c.CatagoryId.ToString() };
            ViewBag.CatagoryId = catagories;

            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Submit(ArticleSubmitViewModel articlevm)
        {
            var catagories = from c in cMgr.ListCatagories()
                             select new SelectListItem { Text = c.Name, Value = c.CatagoryId.ToString() };
            ViewBag.CatagoryId = catagories;
            // validate
            if (!ModelState.IsValid)
            {

                return View();
            }

            // convert vm to dm
            Article article = new Article();
            article.Title = articlevm.Title;
            article.Url = articlevm.Url;
            article.Description = articlevm.Description;
            article.CatagoryId = articlevm.CatagoryID;

            // fill the remaining properties
            article.IsApproved = false;
            article.DateSubmited = DateTime.Now;
            if (User.Identity.IsAuthenticated)
                article.Submiter = User.Identity.Name;
            else
                article.Submiter = "Unknow";

            // submit to domain
            aMgr.SubmitArticle(article);
            TempData["Message"] = $"Article {article.Title} submited for review. Thanks";
            return View(new ArticleSubmitViewModel());
        }

        [Authorize(Roles = "admin")]
        public ActionResult ReviewArticles()
        {
            var articlesForReview = from a in aMgr.GetArticlesForReview()
                                    select new ReviewArticleViewModel
                                    {
                                        Id = a.Id,
                                        Title = a.Title,
                                        Url = a.Url,
                                        Catagory = a.Catagory.Name,
                                        WhenSubmited = a.DateSubmited.Humanize(false),
                                        Submiter = a.Submiter,
                                    };
            return View(articlesForReview);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Approve(List<int> articlIds)
        {
            aMgr.ApproveArticles(articlIds);
            TempData["Message"] = $"{articlIds.Count} Articles Approved Successfully";
            // send email to the submiter about this action
            return RedirectToAction("ReviewArticles");
        }
        [Authorize(Roles = "admin")]
        public ActionResult Reject(List<int> articlIds)
        {
            aMgr.RejectArticles(articlIds);
            TempData["Message"] = $"{articlIds.Count} Articles Rejected Successfully";
            // send email to the submiter about this action

            return RedirectToAction("ReviewArticles");
        }
    }
}

KnowledgeHubPortal.WebUI/Controllers/CatagoriesController.cs
using KnowledgeHubPortal.Domain;
using KnowledgeHubPortal.Domain.Entities;
using System.Web.Mvc;

namespace KnowledgeHubPortal.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class CatagoriesController : Controller
    {
        // GET: Catagories

        //private Domain.Data.ICatagoryRepository repo = null;
        private ICatagoriesManager mgr = null;

        //public CatagoriesController()
        //{
        //    repo = new CatagoryRepository();
        //    mgr = new CatagoryManager(repo);
        //}

        public CatagoriesController(ICatagoriesManager mgr)
        {
            this.mgr = mgr;
        }
        public ActionResult Index()
        {
            var catagoryList = mgr.ListCatagories();
            return View(catagoryList);
        }

        // .../catagories/create
        [HttpGet]
        //[AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Catagory catagory)
        {
            // servier side validation
            if (!ModelState.IsValid)
            {
                return View();
            }
            // do not do this - inject with ioc


            mgr.CreateCatagory(catagory);

            TempData["Message"] = $"Catagory {catagory.Name} created successfully...";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            //?????
            // fetch the catagory details based on id
            // send that to view for editing
            var catToEdit = mgr.GetCatagoryById(id);
            return View(catToEdit);
        }
        [HttpPost]
        public ActionResult Edit(Catagory editedCatagory)
        {
            // validate
            if (!ModelState.IsValid)
            {
                return View(editedCatagory);
            }
            // update into db
            mgr.EditCatagory(editedCatagory);
            //return View("Index",mgr.ListCatagories());
            TempData["Message"] = $"Catagory edited successfully...";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(mgr.GetCatagoryById(id));
        }

        public ActionResult ConfirmDelete(int id)
        {
            mgr.DeleteCatagory(id);
            TempData["Message"] = $"Catagory {id} deleted successfully...";
            return RedirectToAction("Index");
        }


    }
}

KnowledgeHubPortal.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Knowledge Hub Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Browse Articles", "Index", "Articles")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Submit Articles", "Submit", "Articles")</li>
                    }

                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                    <li>@Html.ActionLink("Manage Catagories", "Index", "Catagories")</li>
                    <li>@Html.ActionLink("Review Articles", "ReviewArticles", "Articles")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Knowledge Hub Portal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KnowledgeHubPortal.WebUI/Views/Shared/_MyLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_MyLayout</title>
</head>
<body>
    <div> 
        <h1>This is header</h1>
    </div>
    <div>
        @RenderBody()
    </div>
    <div>
        <h3>This is footer</h3>
    </div>
</body>
</html>

KnowledgeHubPortal.WebUI/Views/Shared/_SearchArticlesPartial.cshtml
<form action="/Articles/Index" method="post">
    <input type="text" name="searchTerm" placeholder="Enter text to search articles" />
    <input type="submit" name="btnSearch" value="Search Articles" class="btn btn-info" />
</form>